### ISSUE TITLE
Cannot autoupload to PyPI as the pypa action does not belong to bkkas

### ISSUE THREAD

**Issue by Sondren1288** [bkkas/ais#2]
pypa/gh-action-pypi-publish@release/v1 is not allowed to be used in bkkas/ais. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: helm/chart-releaser-action@*, robburger/terraform-pr-commenter@v1, actions-hub/kubectl@master.

**Comment by epa095** [comment]
Two possible solution:
1. Clone the desired GH action into this repo and use at as a "Local" action. This is done in on of Evinys other open source repos: https://github.com/bkkas/elhub-python-sdk/tree/main/.github dissadvantage of this is that its a bit more work to update to new versions of the action if needed in the future.
2. Get Eviny to whitelist this particular action. I have asked about getting this done, will report back.

**Comment by epa095** [comment]
@Sondren1288  The action is now approved in Eviny, so should work! I close this, reopen it if it turns out I am wrong.
